import Head from 'next/head'
import styles from '../styles/Home.module.css'
import HeroComp from '../components/Hero/index';
import FeaturesComp from '../components/Features';
import DevStepsComp from '../components/DevSteps';
import LastWorksComp from '../components/LastWorks';
import RequestComp from '../components/Request';
import NewsComp from '../components/News';
import FooterComp from '../components/Footer';
export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <HeroComp />
      <FeaturesComp />
      <DevStepsComp />
      <LastWorksComp />
      <RequestComp />
      <NewsComp />
      <FooterComp />
    </div>
  )
}
